---
TYPO3:
  TSConfig:
    TCEFORM:
      tt_content:
        set1:
          title: 'Set 1'
          description: 'Elements and plugins enabled for editors on regular pages with backend layout 17'
          operator: '||'
          userFunctions:
            - isInUserGroup(2)
            - hasDoktype(1)
            - hasBackendLayout(homepage)
            - hasColumnPosition(2)
          contentElements:
            - image
            - textpic
            - companytoolbox_cardgrid
            - gridelements_view
            - image
            - text
            - textpic
            - list
            - bullets
            - table
            - html
            - div
          plugins:
            - companycalendar_pi1
            - companycalendar_pi2
        Set2:
          contentElements:
            - image
            - textpic
            - gridelements_view
            - image
            - text
            - textpic
            - list
            - bullets
            - table
            - html
            - div
          plugins: []
        textpic:
          userFunctions:
            - isContentType(4)
